name: auti_warrior_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: 1.3.0
  shared_preferences: ^2.2.2
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.2
  flutter_svg: ^2.0.15
  font_awesome_flutter: ^10.8.0
  flutter_native_splash: ^2.4.2
  url_launcher: ^6.3.1
  stomp_dart_client: ^2.1.3
  dio: ^5.8.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: ADLaM Display
      fonts:
        - asset: assets/fonts/ADLaMDisplay-Regular.ttf

flutter_native_splash:
  color: "#97a5b2"
  image: assets/images/splash.png
  android: true 
  fullscreen: true
  android_gravity: fill
  ios: true  
  ios_content_mode: scaleAspectFill